apiVersion: v1
kind: Secret
metadata:
  name: finishline-mysql-secret
  namespace: database
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=   # base64 encoded: echo -n 'password' | base64
  MYSQL_PASSWORD: dXNlcnBhc3M=       # base64 encoded: echo -n 'userpass' | base64