apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: databases
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.1
          args: ["start-dev"]  # use "start" in production
          ports:
            - containerPort: 8080
          env:
            - name: KC_DB
              value: mysql
            - name: KC_DB_URL
              value: jdbc:mysql://mysql-0.mysql.databases.svc.cluster.local:3306/finishlinedb
            - name: KC_DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: finishline-mysql-cm
                  key: MYSQL_USER
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: finishline-mysql-secret
                  key: MYSQL_PASSWORD
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10